name: build-go

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * 1'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.x'
      - name: Update README.md
        run: go run update_readme.go
      - name: Commit change & Push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "bot: update README.md automatically"
          git push
