name: build-py

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Shell
    - name: Update README.md
      run: sh update_readme.sh
    - name: Commit change & Push
      run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "bot: update README.md automatically"
          git push
